spring:
  application:
    name: spring-catalog

  datasource:
    url: jdbc:h2:mem:spring-catalog
    username: user
    password: secret
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: secret